version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: unoclin-postgres15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: unoclin
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - unoclin-net

  backend:
    build: .
    container_name: unoclin-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/unoclin
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - unoclin-net

volumes:
  pgdata:

networks:
  unoclin-net:
